### ISSUE TITLE
Auto-reconnect if connection is lost

### ISSUE THREAD

**Issue by itzo** [itzo/slack-beebot#3]
Bot should reconnect after a network outage.

```
Traceback (most recent call last):
  File "./beebot.py", line 181, in <module>
    reaction, from_user, to_user = parse_event(sc.rtm_read())
  File "/home/username/beebot/local/lib/python2.7/site-packages/slackclient/_client.py", line 120, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/username/beebot/local/lib/python2.7/site-packages/slackclient/_server.py", line 138, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/username/beebot/local/lib/python2.7/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/home/username/beebot/local/lib/python2.7/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/username/beebot/local/lib/python2.7/site-packages/websocket/_core.py", line 341, in recv_data_frame
    self.pong(frame.data)
  File "/home/username/beebot/local/lib/python2.7/site-packages/websocket/_core.py", line 285, in pong
    self.send(payload, ABNF.OPCODE_PONG)
  File "/home/username/beebot/local/lib/python2.7/site-packages/websocket/_core.py", line 234, in send
    return self.send_frame(frame)
  File "/home/username/beebot/local/lib/python2.7/site-packages/websocket/_core.py", line 259, in send_frame
    l = self._send(data)
  File "/home/username/beebot/local/lib/python2.7/site-packages/websocket/_core.py", line 423, in _send
    return send(self.sock, data)
  File "/home/username/beebot/local/lib/python2.7/site-packages/websocket/_socket.py", line 116, in send
    return sock.send(data)
  File "/usr/lib/python2.7/ssl.py", line 709, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe
```

**Comment by itzo** [comment]
resolved with 60235fedd96f242e84f87402f3e58bff2ec0d3d8
